apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-app
  labels:
    app: flask-sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-sentiment
  template:
    metadata:
      labels:
        app: flask-sentiment
    spec:
      containers:
      - name: flask-sentiment
        image: your-dockerhub-username/flask_sentiment:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

