apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
spec:
  type: NodePort
  selector:
    app: flask-sentiment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30100
