name: CI/CD Pipeline for Flask Sentiment Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Use a self-hosted runner with Minikube installed and configured

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        echo "No tests defined yet!"

    - name: Build Docker image
      run: |
        docker build -t flask-vader-sentiment .

    - name: Push Docker image to Minikube
      run: |
        eval $(minikube docker-env) # Use Minikube's Docker daemon
        docker tag flask-vader-sentiment flask-vader-sentiment:latest

  deploy:
    runs-on: self-hosted  # Ensure Minikube is running on this runner
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ensure Minikube is running
      run: |
        minikube start --wait
        minikube status

    - name: Update Kubernetes Deployment
      run: |
        kubectl apply -f k8s/deployment.yaml # Ensure you have a deployment manifest
        kubectl set image deployment/flask-sentiment flask-sentiment=flask-vader-sentiment:latest
        kubectl rollout restart deployment/flask-sentiment

